# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "laravel"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.network "forwarded_port", guest: 80, host: 9876
  config.vm.network "public_network"
  config.vm.provision :shell, :path => "../_assets/update.sh"
  config.vm.provision :shell, :path => "../_assets/vim.sh"
  config.vm.provision :shell, :path => "../_assets/unzip.sh"
  config.vm.provision :shell, :path => "../_assets/vsftpd.sh"
  config.vm.provision :shell, :path => "../_assets/apache.sh"
  config.vm.provision :shell, :path => "../_assets/php.sh"
  config.vm.provision :shell, :path => "../_assets/mysql.sh"
  config.vm.provision :shell, :path => "../_assets/curl.sh"
  config.vm.provision :shell, :path => "../_assets/git.sh"
  config.vm.provision :shell, :path => "../_assets/composer.sh"
  config.vm.provision :shell, :path => "../_assets/laravel.sh"
end
